---

# Sets up a server with edx services that can't be deployed
# behind an ELB together with the main django app.

- name: Configure edx service instance(s)
  hosts: services
  sudo: True
  gather_facts: True
  vars:
    migrate_db: "yes"
    openid_workaround: True
    # These should stay false for the public AMI
    COMMON_ENABLE_DATADOG: False
    COMMON_ENABLE_SPLUNKFORWARDER: False
    ENABLE_LEGACY_ORA: !!null
  roles:
    - security
    - { role: 'rabbitmq', rabbitmq_ip: '' }
    - oraclejdk
    - elasticsearch
    - edx_ansible
